package template

const NotEditMark = `
// Code generated by github.com/ZaneXie/gen. DO NOT EDIT.
// Code generated by github.com/ZaneXie/gen. DO NOT EDIT.
// Code generated by github.com/ZaneXie/gen. DO NOT EDIT.
`

const Header = NotEditMark + `
package {{.Package}}

import(
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"
	"gorm.io/gorm/clause"

	"github.com/ZaneXie/gen"
	"github.com/ZaneXie/gen/field"
	"github.com/ZaneXie/gen/helper"
	{{ if .StructPkgPath  }}"{{.StructPkgPath}}"{{ end }}
)
`

const UnitTestHeader = NotEditMark + `
package {{.}}

import(
	"context"
	"fmt"
	"strconv"
	"testing"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

`
